apiVersion: apps/v1
kind: Deployment
metadata:
  name: item
  namespace: warehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: item
  template:
    metadata:
      labels:
        app: item
    spec:
      containers:
      - name: item
        image: warehouse-item:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8093
        env:
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: KAFKA_BOOTSTRAPADDRESS
          value: "kafka:9092"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://host.docker.internal:3306/testDb"
        - name: SPRING_REDIS_HOST
          value: "redis"
        - name: SPRING_REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: item
  namespace: warehouse
spec:
  ports:
    - port: 8093
      targetPort: 8093
  selector:
    app: item
